language: cpp
script: 
   - mkdir build
   - cd build
   - cmake ..
   - make
   - make package
dist: bionic
sudo: false
git:
  depth: 1


matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
          - "ubuntu-toolchain-r-test"
          packages:
          - "g++-4.9"
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - "g++-5"
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - "g++-6"
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - "g++-7"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          packages:
            - "clang-4.0"
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      addons:
        apt:
          packages:
            - "clang-5.0"
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      addons:
        apt:
          packages:
            - "clang-6.0"
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - eval "${CC} --version"
    - eval "${CXX} --version"
